name: Build & Push TuneUp Web Client

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            tuneupwebclient/tuneup-frontend:latest
            tuneupwebclient/tuneup-frontend:${{ github.sha }}
          cache-from: type=registry,ref=tuneupwebclient/tuneup-frontend:cache
          cache-to:   type=registry,ref=tuneupwebclient/tuneup-frontend:cache,mode=max

      - name: Set outputs
        run: |
          echo "IMAGE_TAG=tuneupwebclient/tuneup-frontend:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "IMAGE_VERSION=${{ github.sha }}"           >> $GITHUB_OUTPUT

    outputs:
      IMAGE_TAG: ${{ steps.build-and-push.outputs.IMAGE_TAG }}
      IMAGE_VERSION: ${{ steps.build-and-push.outputs.IMAGE_VERSION }}
